name = "PowerGraphics"
uuid = "5f7eddb3-86b1-49e8-a95a-ddc0f45eea41"
authors = ["Lily Hanig", "Clayton Barrows", "Jose Daniel Lara"]
version = "0.2.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
Colors = "0.11"
julia = "1"
