[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
PowerGraphics = "5f7eddb3-86b1-49e8-a95a-ddc0f45eea41"

[compat]
Documenter = "^1.8"
julia = "^1.6"
